- Logout now works for blocked and expired users
datamatica-pl/traccar-api pull request #111
Opened 2017-09-04 12:50 UTC by franiis

2017-09-04 13:16 UTC, UZamkniete requested changes

2017-09-04 13:16 UTC, UZamkniete commented on src/main/java/pl/datamatica/traccar/api/auth/BasicAuthFilter.java
> +            if (req.attribute(RequestContext.REQUEST_FIELD_ERROR_DTO) != null && rc.isRequestForImeiManager(request)) {
Na pewno miało być  `!= null`?

2017-09-04 13:40 UTC, franiis commented on src/main/java/pl/datamatica/traccar/api/auth/BasicAuthFilter.java
> +            if (req.attribute(RequestContext.REQUEST_FIELD_ERROR_DTO) != null && rc.isRequestForImeiManager(request)) {
Masz rację, powinno być odwrotnie

2017-09-05 06:01 UTC, UZamkniete approved these changes

2017-09-05 06:02 UTC, merged